# Generated by Django 3.2.9 on 2021-11-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField()),
                ('CatID', models.IntegerField(max_length=255)),
                ('CAST', models.TextField()),
                ('DESCRIPTION', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('MID', models.IntegerField()),
                ('UID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField()),
                ('MID', models.IntegerField()),
                ('UID', models.IntegerField()),
                ('LIKES', models.IntegerField()),
                ('DISLIKES', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
                ('EMAIL', models.CharField(max_length=255)),
                ('CONTACT', models.CharField(max_length=10)),
                ('PASSWORD', models.CharField(max_length=60)),
            ],
        ),
    ]
