# Generated by Django 3.2.9 on 2021-11-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='CatID',
            field=models.IntegerField(),
        ),
    ]
