# Generated by Django 3.2.9 on 2021-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0003_auto_20211112_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='EMAIL',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
